;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Nov 16 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;
; German E Felisarta III	16101002	CpE3104 Grp 1
;
;====================================================================

DATA SEGMENT     
    
PORTA	EQU 0F0H	; PORT ADDRESSES
PORTB	EQU 0F2H	
PORTC	EQU 0F4H	
COM_REG EQU 0F6H

				                            
DATA ENDS  

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE
   
START:  

   MOV DX, COM_REG 	 ; STORE COMMAND REGISTER ADDRESS
   MOV AL, 89H
   OUT DX, AL
   
PRINT:			;PRINT HELLO STRING
   CALL INIT_LCD
   MOV AL, 0C6H
   CALL INST_CTRL

   MOV AL, 'H'
   CALL DATA_CTRL
   MOV AL, 'E'
   CALL DATA_CTRL
   MOV AL, 'L'
   CALL DATA_CTRL
   MOV AL, 'L'
   CALL DATA_CTRL
   MOV AL, 'O'
   CALL DATA_CTRL
   MOV AL, '!'
   CALL DATA_CTRL
   HLT

INIT_LCD PROC NEAR
   MOV AL, 38H
   CALL INST_CTRL
   MOV AL, 0CH
   CALL INST_CTRL
   MOV AL, 01H
   CALL INST_CTRL
   MOV AL, 06H
   CALL INST_CTRL
 INIT_LCD ENDP
 
INST_CTRL PROC NEAR
   MOV DX, PORTA
   OUT DX, AL
   MOV DX, PORTB
   MOV AL, 02H
   OUT DX, AL
   CALL DELAY
   
   MOV DX, PORTB
   MOV AL, 0H
   OUT DX, AL
INST_CTRL ENDP

DATA_CTRL PROC NEAR
   MOV DX, PORTA
   OUT DX, AL
   MOV DX, PORTB
   MOV AL, 03H
   OUT DX, AL
   CALL DELAY
   MOV DX, PORTB
   MOV AL, 01H
   OUT DX, AL   
   
   
DATA_CTRL ENDP

DELAY PROC NEAR
   MOV CX, 0FFFH  
   
   DELAY_LOOP: 
   
      DEC CX
      CMP CX, 00H
      JNZ DELAY_LOOP     
              
   RET   
   
   
DELAY ENDP
      
CODE ENDS
END