;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Nov 16 2020
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;
; German E Felisarta III	16101002	CpE3104 Grp 1
;
;====================================================================
DATA SEGMENT   
   PORTA EQU 0F0H	; PORT ADDRESSES   
   PORTB EQU 0F2H	   
   PORTC EQU 0F4H	 
   COM_REG EQU 0F6H	
DATA ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
   MOV DX, COM_REG	   ; STORE COMMAND REGISTER ADDRESS
   MOV AL, 89H		
   OUT DX, AL
   CALL INIT_LCD
   
MAIN:
   CALL KEYPRESS
   MOV AH, AL          
   MOV AL, 01H         ; CLEAR
   CALL INST_CTRL      
   MOV AL, 0CAH        
   CALL INST_CTRL      
   MOV AL, AH          
   XOR AL, 0C0H        
   CALL DATA_CTRL      ; DISPLAY TO LCD
   JMP MAIN	           ; LOOP
	 
INST_CTRL PROC NEAR
    MOV DX, PORTA       
    OUT DX, AL          
    MOV DX, PORTB       
    MOV AL, 02H         
    OUT DX, AL          
    CALL DELAY          
    MOV DX, PORTB       
    MOV AL, 00H         
    OUT DX, AL          
    RET
INST_CTRL ENDP

INIT_LCD PROC NEAR
    MOV AL, 38H		
    CALL INST_CTRL	
    MOV AL, 0CH         
    CALL INST_CTRL	
    MOV AL, 01H         
    CALL INST_CTRL	
    MOV AL, 06H		
    CALL INST_CTRL	
    RET
INIT_LCD ENDP

DATA_CTRL PROC NEAR
    MOV DX, PORTA       
    OUT DX, AL		
    MOV DX, PORTB       
    MOV AL, 03H         
    OUT DX, AL          
    CALL DELAY          
    MOV DX, PORTB       
    MOV AL, 01H         
    OUT DX, AL          
    RET
DATA_CTRL ENDP

DELAY PROC NEAR		; TIME DELAY (optional)
   MOV CX, 0FFFh
   DELAY_LOOP:
      DEC CX
      CMP CX, 00H
      JNZ DELAY_LOOP
   RET
DELAY ENDP

KEYPRESS PROC      
   CHECK:		; INPUT FOR NUMPAD
      XOR AL, AL
      IN AL, PORTC
      CMP AL, 0FFH
      JE CHECK
      CALL ADJUST	; ADJUST ADJUSTS NUMPAD BINDINGS TO MATCH MM74C
   RET
KEYPRESS ENDP

ADJUST PROC                
   CMP AL, 0F0H               
   JE INCREMENT               
   CMP AL, 0F1H               
   JE INCREMENT               
   CMP AL, 0F2H               
   JE INCREMENT
   CMP AL, 0F8H
   JE DECREMENT
   CMP AL, 0F9H
   JE DECREMENT
   CMP AL, 0FAH
   JE DECREMENT
   CMP AL, 0FDH
   JE ZERO
   JMP LOOP_END

   INCREMENT:
      INC AL
      JMP LOOP_END
   DECREMENT:
      DEC AL
      JMP LOOP_END
   ZERO:
      MOV AL, 0F0H
   LOOP_END:
      RET
ADJUST ENDP

CODE	ENDS
        END START